### ISSUE TITLE
Perk Shaders Initial X-Position Values Off-Screen

### ISSUE THREAD

**Issue by MotoLegacy** [ApexModder/T7-Mod#3]
**Note: This build of the game was linked manually by cloning the repository!**

The initial X coordinate for Perk Shaders are out of bounds, as seen in the screenshot below. The first perk is off-screen completely and the second is only half-way in-bounds. I have tried resolutions of both 1440x900 and 1280x720, they yielded the same result:

![00apex-perk](https://user-images.githubusercontent.com/26030250/67996294-17839680-fc25-11e9-8d7b-79d99357beef.png)

**Comment by ApexModder** [comment]
Do you play fullscreen? Cause while developing the mod, the perk icons line up correctly when playing windowed 1280x720

**Comment by MotoLegacy** [comment]
> Do you play fullscreen? While developing the mod, i play windowed 1280x720 and the perk icons line up correctly.

Can confirm, does work in windowed 1280x720.

![shot0006](https://user-images.githubusercontent.com/26030250/67997178-69c6b680-fc29-11e9-9985-6a030e2b7984.jpg)
